name: test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          sudo apt-get -y update
          sudo apt-get install -y make
          make install
      - name: Build apps
        run: |
          make clean
          make fmt
          make build
      - name: Run apps
        run: |
          make run
